export const constructorActions = {
  ADD_INGREDIENT_TO_BURGER: "ADD_INGREDIENT_TO_BURGER",
  ADD_BUN_TO_BURGER: "ADD_BUN_TO_BURGER",
  ADD_INGREDIENT_TO_BURGER: "ADD_INGREDIENT_TO_BURGER",
  REMOVE_INGREDIENT_FROM_BURGER: "REMOVE_INGREDIENT_FROM_BURGER",
  CHANGE_BURGER_INGREDIENT: "CHANGE_BURGER_INGREDIENT",
  CLEAR_ORDER: "CLEAR_ORDER",
  SET_ORDER_DETAILS: "SET_ORDER_DETAILS",
  SET_BUN: "SET_BUN",
};
