
  export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
  export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";
  export const SET_SORTED_INGREDIENTS: "SET_All_INGREDIENTS" = "SET_All_INGREDIENTS";
  export const SET_INGREDIENT_DETAILS: "SET_INGREDIENT_DETAILS" = "SET_INGREDIENT_DETAILS";
  export const INCREASE_INGREDIENT_QTY: "INCREASE_INGREDIENT_QTY" = "INCREASE_INGREDIENT_QTY";
  export const DECREASE_INGREDIENT_QTY: "DECREASE_INGREDIENT_QTY" = "DECREASE_INGREDIENT_QTY";
  export const INGREDIENTS_FETCHING: "INGREDIENTS_FETCHING" = "INGREDIENTS_FETCHING";


export const ingredientsActions = {
  GET_INGREDIENTS_SUCCESS,
  GET_INGREDIENTS_FAILED,
  SET_SORTED_INGREDIENTS,
  SET_INGREDIENT_DETAILS,
  INCREASE_INGREDIENT_QTY,
  DECREASE_INGREDIENT_QTY,
  INGREDIENTS_FETCHING,
};

