export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILED: "POST_ORDER_FAILED" = "POST_ORDER_FAILED";
export const POST_ORDER_FETCHING: "POST_ORDER_FETCHING" = "POST_ORDER_FETCHING";

export const orderActions = {
  POST_ORDER_SUCCESS,
  POST_ORDER_FAILED,
  POST_ORDER_FETCHING,
};
