export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILED: "POST_ORDER_FAILED" = "POST_ORDER_FAILED";
export const POST_ORDER_FETCHING: "POST_ORDER_FETCHING" = "POST_ORDER_FETCHING";
export const SET_ORDER_FEED: "SET_ORDER_FEED" = "SET_ORDER_FEED";

export const orderActions = {
  POST_ORDER_SUCCESS,
  POST_ORDER_FAILED,
  POST_ORDER_FETCHING,
  SET_ORDER_FEED,
};
