export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" =
  "WS_CONNECTION_CLOSED";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";
export const WS_SEND_MESSAGE: "WS_SEND_MESSAGE" = "WS_SEND_MESSAGE";
export const WS_GET_MESSAGE_SUCCESS: "WS_GET_MESSAGE_SUCCESS" =
  "WS_GET_MESSAGE_SUCCESS";
export const WS_GET_MESSAGE_FAILED: "WS_GET_MESSAGE_FAILED" =
  "WS_GET_MESSAGE_FAILED";
export const WS_CONNECTION_CLOSE: "WS_CONNECTION_CLOSE" = "WS_CONNECTION_CLOSE";

export const WS_AUTH_CONNECTION_START: "WS_AUTH_CONNECTION_START" =
  "WS_AUTH_CONNECTION_START";
export const WS_AUTH_CONNECTION_SUCCESS: "WS_AUTH_CONNECTION_SUCCESS" =
  "WS_AUTH_CONNECTION_SUCCESS";
export const WS_AUTH_CONNECTION_ERROR: "WS_AUTH_CONNECTION_ERROR" =
  "WS_AUTH_CONNECTION_ERROR";
export const WS_AUTH_CONNECTION_CLOSED: "WS_AUTH_CONNECTION_CLOSED" =
  "WS_AUTH_CONNECTION_CLOSED";
export const WS_AUTH_GET_MESSAGE: "WS_AUTH_GET_MESSAGE" = "WS_AUTH_GET_MESSAGE";
export const WS_AUTH_SEND_MESSAGE: "WS_AUTH_SEND_MESSAGE" =
  "WS_AUTH_SEND_MESSAGE";
export const WS_AUTH_GET_MESSAGE_SUCCESS: "WS_AUTH_GET_MESSAGE_SUCCESS" =
  "WS_AUTH_GET_MESSAGE_SUCCESS";
export const WS_AUTH_GET_MESSAGE_FAILED: "WS_AUTH_GET_MESSAGE_FAILED" =
  "WS_AUTH_GET_MESSAGE_FAILED";
export const WS_AUTH_CONNECTION_CLOSE: "WS_AUTH_CONNECTION_CLOSE" =
  "WS_AUTH_CONNECTION_CLOSE";

export const wsActions = {
  WS_CONNECTION_CLOSED,
  WS_CONNECTION_ERROR,
  WS_CONNECTION_START,
  WS_CONNECTION_SUCCESS,
  WS_SEND_MESSAGE,
  WS_GET_MESSAGE,
  WS_GET_MESSAGE_SUCCESS,
  WS_GET_MESSAGE_FAILED,
  WS_CONNECTION_CLOSE,
  WS_AUTH_CONNECTION_CLOSED,
  WS_AUTH_CONNECTION_ERROR,
  WS_AUTH_CONNECTION_START,
  WS_AUTH_CONNECTION_SUCCESS,
  WS_AUTH_SEND_MESSAGE,
  WS_AUTH_GET_MESSAGE,
  WS_AUTH_GET_MESSAGE_SUCCESS,
  WS_AUTH_GET_MESSAGE_FAILED,
  WS_AUTH_CONNECTION_CLOSE,
};

export const wsActionsMiddleware = {
  wsStart: WS_CONNECTION_START,
  wsOpen: WS_CONNECTION_SUCCESS,
  wsClose: WS_CONNECTION_CLOSE,
  wsError: WS_CONNECTION_ERROR,
  wsGetMessage: WS_GET_MESSAGE_SUCCESS,
  wsGetMessageFailed: WS_GET_MESSAGE_FAILED,
  wsSendMessage: WS_SEND_MESSAGE,
};

export const wsActionsAuthMiddleware = {
  wsStart: WS_AUTH_CONNECTION_START,
  wsOpen: WS_AUTH_CONNECTION_SUCCESS,
  wsClose: WS_AUTH_CONNECTION_CLOSE,
  wsError: WS_AUTH_CONNECTION_ERROR,
  wsGetMessage: WS_AUTH_GET_MESSAGE_SUCCESS,
  wsGetMessageFailed: WS_AUTH_GET_MESSAGE_FAILED,
  wsSendMessage: WS_AUTH_SEND_MESSAGE,
};
